### ISSUE TITLE
Cxxsat error on MacOS

### ISSUE THREAD

**Issue by phamhnh** [vedadux/cxxsat#1]
Cxxsat error on MacOS with cocoverif test (tutorial at Crypto Summer School 2024 in Vodice). 
System information:
* MacOS Sonoma 14.4.1
* Apple clang version 15.0.0 (clang-1500.3.9.4)
* Target: arm64-apple-darwin23.4.0
* Thread model: posix

<img width="1043" alt="Screenshot 2024-06-07 at 17 12 05" src="https://github.com/vedadux/cxxsat/assets/100359508/9e5520bc-2d6b-419d-ba26-fcf9a10cb70a">

**Comment by dop-amin** [comment]
Hi, I tried to fix this by installing the `gcc` `g++` instead of `clang` from homebrew. 
I then switched `CXX` in `Makefile` to `g++-14` and added `set(CMAKE_CXX_COMPILER g++-14)` in `CMakeLists.txt`.

After that, I get the following message in a loop when running `make sca_masked_xor` (for the summer school exercise):
```
-- The C compiler identification is AppleClang 15.0.0.15000100
-- The CXX compiler identification is AppleClang 15.0.0.15000100
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Adding external Cadical target
-- Configuring done (0.4s)
You have changed variables that require your cache to be deleted.
Configure will be re-run and you may have to reset some variables.
The following variables have changed:
CMAKE_CXX_COMPILER= /Library/Developer/CommandLineTools/usr/bin/c++
CMAKE_CXX_COMPILER= /Library/Developer/CommandLineTools/usr/bin/c++
```

Maybe I did not do enough to fully switch the compiler to the `gcc` one  but, just leaving this here to report what we already tried.

**Comment by vedadux** [comment]
The dependence on stdlibc++ has been removed here. It should be fixed now.
